name: Generate Commit Sculpture
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Workflow pushes changes back to the repo.
      # The push step requires `contents: write` permission.
      # If the default GITHUB_TOKEN lacks this, supply a PAT via
      # `GH_PAGES_WRITE_TOKEN` and rotate it periodically.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Generate model
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python scripts/generate_commit_sculpture.py --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }} --token $GH_TOKEN --output models/commit_sculpture.glb
      - name: Commit model
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add models/commit_sculpture*.glb
          git commit -m "Update commit sculpture [skip ci]" || echo "No changes"
          git pull --rebase
          git push
